server:
  port: 8888
spring:  profiles:    active: native
  cloud:    config:      server:        native:          #searchLocations: file:///Users/johncarnell1/book/native_cloud_apps/ch4-config-managment/confsvr/src/main/resources/config/licensingservice
          searchLocations: C:\devenv\jasdhali\springbootmisc\SpringMicroSVCInAction\confsvr\src\main\resources\config\licensingservice\licensingservice.yml               