server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        #native:
        #  searchLocations: file:///c/devenv/jasdhali/SpringMicroSVCInAction/confsvr/src/main/resources/config//licensingservice
        git:
          uri: https://github.com/jasdhali/config-repo/
          searchPaths: licensingservice
          username: jasdhali
          password: S@hajKa4r
               